

function(eth_show_dependency DEP NAME)
    get_property(DISPLAYED GLOBAL PROPERTY ETH_${DEP}_DISPLAYED)
    if (NOT DISPLAYED)
        set_property(GLOBAL PROPERTY ETH_${DEP}_DISPLAYED TRUE)
        message(STATUS "${NAME} headers: ${${DEP}_INCLUDE_DIRS}")
        message(STATUS "${NAME} lib   : ${${DEP}_LIBRARIES}")
        if (NOT("${${DEP}_DLLS}" STREQUAL ""))
            message(STATUS "${NAME} dll   : ${${DEP}_DLLS}")
        endif() 
    endif()
endfunction()


function(eth_use TARGET REQUIRED)
	if (NOT TARGET ${TARGET})
		message(FATAL_ERROR "eth_use called for non existing target ${TARGET}")
	endif()

	foreach(MODULE ${ARGN})
		string(REPLACE "::" ";" MODULE_PARTS "${MODULE}")
		list(GET MODULE_PARTS 0 MODULE_MAIN)
		list(LENGTH MODULE_PARTS MODULE_LENGTH)
		if (MODULE_LENGTH GREATER 1)
			list(GET MODULE_PARTS 1 MODULE_SUB)
		endif()
		# TODO: check if file exists if not, throws FATAL_ERROR with detailed description
		get_target_property(TARGET_APPLIED ${TARGET} TARGET_APPLIED_${MODULE_MAIN}_${MODULE_SUB})
		if (NOT TARGET_APPLIED)
			include(Use${MODULE_MAIN})
			set_target_properties(${TARGET} PROPERTIES TARGET_APPLIED_${MODULE_MAIN}_${MODULE_SUB} TRUE)
			eth_apply(${TARGET} ${REQUIRED} ${MODULE_SUB})
		endif()
	endforeach()
endfunction()
